### ISSUE TITLE
盒模型宽度计算

### ISSUE THREAD

**Issue by Ricoloshare** [Ricoloshare/issue#4]
- clientWidth和clientHeigh 、 clientTop和clientLeft
1. clientWidth = width+左右padding
2. clientHeigh = height + 上下padding 
3. clientTop = boder.top(上边框的宽度)
4. clientLeft = boder.left(左边框的宽度)
- offsetWidth和offsetHight 、 offsetTop和offsetLeft
1. offsetWidth = width + 左右padding + 左右boder
2. offsetHeith = height + 上下padding + 上下boder
3. offsetTop：当前元素 上边框 外边缘 到 最近的已定位父级（offsetParent） 上边框 内边缘的 距离。如果父级都没有定位，则分别是到body 顶部 和左边的距离
4. offsetLeft：当前元素 左边框 外边缘 到 最近的已定位父级（offsetParent） 左边框 内边缘的            距离。如果父级都没有定位，则分别是到body 顶部 和左边的距离
- scrollWidth和scrollHeight 、 scrollTop和scrollLeft
1. scrollWidth：获取指定标签内容层的真实宽度（可视区域宽度+被隐藏区域宽度）。
2. scrollHeight：获取指定标签内容层的真实高度（可视区域高度+被隐藏区域高度）
3. scrollTop :内容层顶部 到 可视区域顶部的距离。
4. scrollLeft:内容层左端 到 可视区域左端的距离。

```css
div{
  width: 100px;
  height: 100px;
  padding: 10px; 
  border: 1px solid #ccc;
  margin: 10px;
  box-sizing: border-box;
}
```
上述代码的offsetWidth为100px；

```css
div{
  width: 100px;
  height: 100px;
  padding: 10px; 
  border: 1px solid #ccc;
  margin: 10px;
}
```
上述代码的offsetWidth为122px；
